title: Î»CogLab
SEOTitle: lambdacogito
header-img: "img/about-bg-walle.jpg"
email: chenxm35@gmail.com
url: "https://lambdacogito.github.io"
baseurl: ""

collections_dir: content
collections:
  poems:
    output: true

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: true
github_username:    caesar0301
facebook_username:  caesar0301
twitter_username:   drjaminchen
linkedin_username:  xiamingc

# Build settings
highlighter: rouge
permalink: pretty
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: false
timezone: CN

# Gems
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
#disqus_username: xiamingdotsite

# Netease settings
#netease_comment: false

# Analytics settings
# Baidu Analytics
ba_track_id: 933a7ca2adb3fad09e99a8fc2f538d69

# Sidebar settings
sidebar: true
sidebar-about-description: "Researcher on Knowledge Computing. Ph.D in Behavioral Informatics."
sidebar-avatar: /img/avatar.jpg

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
friends: []
